export const SEED_TEAMS = [
  { name: 'Red Bull Racing', country: 'Austria' },
  { name: 'Scuderia Ferrari', country: 'Italia' },
  { name: 'McLaren F1 Team', country: 'Reino Unido' },
  { name: 'Mercedes-AMG Petronas', country: 'Alemania' },
  { name: 'Aston Martin Aramco', country: 'Reino Unido' },
] as const

export const SEED_DRIVERS = [
  {
    firstName: 'Max',
    lastName: 'Verstappen',
    code: 'VER',
    number: 1,
    country: 'Países Bajos',
    teamName: 'Red Bull Racing',
  },
  {
    firstName: 'Sergio',
    lastName: 'Pérez',
    code: 'PER',
    number: 11,
    country: 'México',
    teamName: 'Red Bull Racing',
  },
  {
    firstName: 'Charles',
    lastName: 'Leclerc',
    code: 'LEC',
    number: 16,
    country: 'Mónaco',
    teamName: 'Scuderia Ferrari',
  },
  {
    firstName: 'Carlos',
    lastName: 'Sainz',
    code: 'SAI',
    number: 55,
    country: 'España',
    teamName: 'Scuderia Ferrari',
  },
  {
    firstName: 'Lando',
    lastName: 'Norris',
    code: 'NOR',
    number: 4,
    country: 'Reino Unido',
    teamName: 'McLaren F1 Team',
  },
  {
    firstName: 'Oscar',
    lastName: 'Piastri',
    code: 'PIA',
    number: 81,
    country: 'Australia',
    teamName: 'McLaren F1 Team',
  },
  {
    firstName: 'Lewis',
    lastName: 'Hamilton',
    code: 'HAM',
    number: 44,
    country: 'Reino Unido',
    teamName: 'Mercedes-AMG Petronas',
  },
  {
    firstName: 'George',
    lastName: 'Russell',
    code: 'RUS',
    number: 63,
    country: 'Reino Unido',
    teamName: 'Mercedes-AMG Petronas',
  },
  {
    firstName: 'Fernando',
    lastName: 'Alonso',
    code: 'ALO',
    number: 14,
    country: 'España',
    teamName: 'Aston Martin Aramco',
  },
  {
    firstName: 'Lance',
    lastName: 'Stroll',
    code: 'STR',
    number: 18,
    country: 'Canadá',
    teamName: 'Aston Martin Aramco',
  },
] as const
